table categories
	lineageTag: c9d42475-4c5c-470e-8cb0-137799d0de40

	column category_id
		dataType: int64
		formatString: 0
		lineageTag: dc44f003-6d59-422f-9137-06bf83431972
		summarizeBy: none
		sourceColumn: category_id

		annotation SummarizationSetBy = Automatic

	column category_name
		dataType: string
		lineageTag: 49150735-0f13-4f89-9de7-ecb04e5c8dda
		summarizeBy: none
		sourceColumn: category_name

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		lineageTag: 41c74210-fe69-44b2-9c19-c0c7750c812b
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	partition categories = m
		mode: import
		source =
				let
				    Kaynak = Csv.Document(File.Contents("C:\Users\AybükeAltuntaş\Downloads\categories.csv"),[Delimiter=",", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Tanıtılan Üst Bilgiler" = Table.PromoteHeaders(Kaynak, [PromoteAllScalars=true]),
				    #"Değiştirilen Tür" = Table.TransformColumnTypes(#"Tanıtılan Üst Bilgiler",{{"category_id", Int64.Type}, {"category_name", type text}, {"description", type text}})
				in
				    #"Değiştirilen Tür"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Gezinme

