table orders
	lineageTag: 5850c3b7-65d1-4dbb-a75e-11cc7b92a5a2

	column order_id
		dataType: int64
		formatString: 0
		lineageTag: 243205fb-b1c9-4d62-a3d5-d060e47225c7
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: int64
		formatString: 0
		lineageTag: 6a1b924c-af85-4cf2-8be3-b391bf0dbb2e
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column seller_id
		dataType: int64
		formatString: 0
		lineageTag: b2763207-15fb-4939-99a0-e42496c39314
		summarizeBy: none
		sourceColumn: seller_id

		annotation SummarizationSetBy = Automatic

	column order_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 112283cb-2f7a-4777-ac84-7dd8a81ba49b
		summarizeBy: none
		sourceColumn: order_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column order_status
		dataType: string
		lineageTag: 451448c3-78fb-43e5-a7ba-5c7378c75d62
		summarizeBy: none
		sourceColumn: order_status

		annotation SummarizationSetBy = Automatic

	column total_amount
		dataType: int64
		formatString: 0
		lineageTag: 6a792f5c-346e-4b17-80e5-b652c09be66f
		summarizeBy: sum
		sourceColumn: total_amount

		annotation SummarizationSetBy = Automatic

	partition orders = m
		mode: import
		source =
				let
				    Kaynak = Csv.Document(File.Contents("C:\Users\AybükeAltuntaş\Downloads\orders.csv"),[Delimiter=",", Columns=6, Encoding=1254, QuoteStyle=QuoteStyle.None]),
				    #"Tanıtılan Üst Bilgiler" = Table.PromoteHeaders(Kaynak, [PromoteAllScalars=true]),
				    #"Değiştirilen Tür" = Table.TransformColumnTypes(#"Tanıtılan Üst Bilgiler",{{"order_id", Int64.Type}, {"customer_id", Int64.Type}, {"seller_id", Int64.Type}, {"order_date", type datetime}, {"order_status", type text}, {"total_amount", Int64.Type}}),
				    #"Değiştirilen Tür1" = Table.TransformColumnTypes(#"Değiştirilen Tür",{{"order_date", type date}})
				in
				    #"Değiştirilen Tür1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Gezinme

