table categories
	lineageTag: 7063ddb8-db47-42f9-858a-90bba91b5f5f

	column category_id
		dataType: int64
		formatString: 0
		lineageTag: db55a65c-44d4-4600-bcbe-6f7ab78a6ad9
		summarizeBy: none
		sourceColumn: category_id

		annotation SummarizationSetBy = Automatic

	column category_name
		dataType: string
		lineageTag: 5d078812-bf8e-4590-b531-b8fcf56c0a5b
		summarizeBy: none
		sourceColumn: category_name

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		lineageTag: 85ce16d7-0c71-4911-adb9-350278e29b3e
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	partition categories = m
		mode: import
		source =
				let
				    Kaynak = anasorgu,
				    #"categories csv_https://mayasoftbilgisistemleri-my sharepoint com/personal/aybuke_altuntas_ensight_com_tr/Documents/salesdata/" = Kaynak{[Name="categories.csv",#"Folder Path"="https://mayasoftbilgisistemleri-my.sharepoint.com/personal/aybuke_altuntas_ensight_com_tr/Documents/salesdata/"]}[Content],
				    ImportedCSV = Csv.Document(#"categories csv_https://mayasoftbilgisistemleri-my sharepoint com/personal/aybuke_altuntas_ensight_com_tr/Documents/salesdata/",[Delimiter=",", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Tanıtılan Üst Bilgiler" = Table.PromoteHeaders(ImportedCSV, [PromoteAllScalars=true]),
				    #"Değiştirilen Tür" = Table.TransformColumnTypes(#"Tanıtılan Üst Bilgiler",{{"category_id", Int64.Type}, {"category_name", type text}, {"description", type text}})
				in
				    #"Değiştirilen Tür"

	annotation PBI_NavigationStepName = Gezinme

	annotation PBI_ResultType = Table

