table customers
	lineageTag: e6f0d75a-0d09-4612-9199-cd5fc7edd59f

	column customer_id
		dataType: int64
		formatString: 0
		lineageTag: 7151511b-c743-4623-8ee5-084d90e68df8
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column first_name
		dataType: string
		lineageTag: 5e2ab8b5-db6a-4064-a1a3-48609122f8c6
		summarizeBy: none
		sourceColumn: first_name

		annotation SummarizationSetBy = Automatic

	column last_name
		dataType: string
		lineageTag: a04a1bf0-dc85-4a75-bae5-31553adeca37
		summarizeBy: none
		sourceColumn: last_name

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: 8aa3be71-c42f-4a14-97b2-bdaef0c7fedc
		summarizeBy: none
		sourceColumn: email

		annotation SummarizationSetBy = Automatic

	column phone
		dataType: int64
		formatString: 0
		lineageTag: a7418f6e-25e4-482f-979d-b0430fb39245
		summarizeBy: sum
		sourceColumn: phone

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: cd220521-56dc-423f-a1d2-3f6ac744523f
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column created_at
		dataType: dateTime
		formatString: Long Date
		lineageTag: f1d41d0f-3f48-4750-8f77-ed69e592e7e5
		summarizeBy: none
		sourceColumn: created_at

		variation Varyasyon
			isDefault
			relationship: d1c2f401-13dd-4515-87e0-638668851559
			defaultHierarchy: LocalDateTable_c32ca93c-3e2c-4d13-af5b-fb1bc08a93ee.'Tarih Hiyerarşisi'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition customers = m
		mode: import
		source =
				let
				    Kaynak = anasorgu,
				    #"customers csv_https://mayasoftbilgisistemleri-my sharepoint com/personal/aybuke_altuntas_ensight_com_tr/Documents/salesdata/" = Kaynak{[Name="customers.csv",#"Folder Path"="https://mayasoftbilgisistemleri-my.sharepoint.com/personal/aybuke_altuntas_ensight_com_tr/Documents/salesdata/"]}[Content],
				    ImportedCSV = Csv.Document(#"customers csv_https://mayasoftbilgisistemleri-my sharepoint com/personal/aybuke_altuntas_ensight_com_tr/Documents/salesdata/",[Delimiter=",", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Tanıtılan Üst Bilgiler" = Table.PromoteHeaders(ImportedCSV, [PromoteAllScalars=true]),
				    #"Değiştirilen Tür" = Table.TransformColumnTypes(#"Tanıtılan Üst Bilgiler",{{"customer_id", Int64.Type}, {"first_name", type text}, {"last_name", type text}, {"email", type text}, {"phone", Int64.Type}, {"city", type text}, {"created_at", type date}})
				in
				    #"Değiştirilen Tür"

	annotation PBI_NavigationStepName = Gezinme

	annotation PBI_ResultType = Table

