table dim_date
	lineageTag: f8aebd88-70c7-4cc1-bdc1-f2c57af13241

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 8e0529ea-5857-4690-9f48-11efaae10042
		summarizeBy: none
		sourceColumn: Date

		variation Varyasyon
			isDefault
			relationship: 9fac95da-5f02-4b7f-811a-e3f566444d64
			defaultHierarchy: LocalDateTable_10dfaeef-799a-4406-a077-686df2dc84cd.'Tarih Hiyerarşisi'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Year
		dataType: int64
		formatString: 0
		lineageTag: e3df2bfa-4096-49b7-8a14-5400274ac0d5
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: int64
		formatString: 0
		lineageTag: 01e96baa-1b88-49dc-baae-6b85cae090ec
		summarizeBy: sum
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: 0df8cc47-f816-477f-af24-90b9b9b435bc
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 61fc80db-d62f-41cf-9dd9-3cccabc6e1d3
		summarizeBy: none
		sourceColumn: MonthName

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		formatString: 0
		lineageTag: 167641a5-e516-4f4e-be4c-05db1b662b2e
		summarizeBy: sum
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: string
		lineageTag: f439fb01-f899-44c4-876e-a8b5ab306886
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column IsWeekend
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: e07ce515-1c9b-43b0-af67-4e697ebad9ec
		summarizeBy: none
		sourceColumn: IsWeekend

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hiyerarşi'
		lineageTag: e1c6fa05-10db-43c3-af9d-6ad2272961a7

		level Date
			lineageTag: a1b4fcd2-6486-4553-9f4a-2566d32d23dc
			column: Date

	partition dim_date = m
		mode: import
		source =
				let
				    Kaynak = Csv.Document(File.Contents("C:\Users\AybükeAltuntaş\Downloads\dim_date.csv"),[Delimiter=",", Columns=8, Encoding=1254, QuoteStyle=QuoteStyle.None]),
				    #"Tanıtılan Üst Bilgiler" = Table.PromoteHeaders(Kaynak, [PromoteAllScalars=true]),
				    #"Değiştirilen Tür" = Table.TransformColumnTypes(#"Tanıtılan Üst Bilgiler",{{"Date", type date}, {"Year", Int64.Type}, {"Quarter", Int64.Type}, {"Month", Int64.Type}, {"MonthName", type text}, {"Day", Int64.Type}, {"DayOfWeek", type text}, {"IsWeekend", type logical}})
				in
				    #"Değiştirilen Tür"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Gezinme

