table dim_date
	lineageTag: 0c75be1d-d8af-4e6b-8c61-129c53c3c66f

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6292a82b-c7c6-4c03-af93-f778d7c5962b
		summarizeBy: none
		sourceColumn: Date

		variation Varyasyon
			isDefault
			relationship: 938f5ea3-cb16-4ec3-9cf5-c0e661427dcc
			defaultHierarchy: LocalDateTable_2cdbf625-cfae-44e0-82a3-32689d224eed.'Tarih Hiyerarşisi'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 852528a6-126a-4882-a356-5ec7dd6ad25d
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: int64
		formatString: 0
		lineageTag: ef1f5eec-6489-4bf5-bbf1-01a0bc86309a
		summarizeBy: sum
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: 17b35055-ebd1-4eb9-b250-23b172564c65
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 4c0b4e8f-36ee-45d5-8686-1c0bb19a1c1f
		summarizeBy: none
		sourceColumn: MonthName

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		formatString: 0
		lineageTag: 13d3b72c-e0f8-43a0-b95d-70db7740a9ae
		summarizeBy: sum
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: string
		lineageTag: 02e7ecd6-58c9-44d2-8979-9b9c7d1345d4
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column IsWeekend
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d4adf017-3b75-465e-b6d0-b99bcd9fb995
		summarizeBy: none
		sourceColumn: IsWeekend

		annotation SummarizationSetBy = Automatic

	partition dim_date = m
		mode: import
		source =
				let
				    Kaynak = anasorgu,
				    #"dim_date csv_https://mayasoftbilgisistemleri-my sharepoint com/personal/aybuke_altuntas_ensight_com_tr/Documents/salesdata/" = Kaynak{[Name="dim_date.csv",#"Folder Path"="https://mayasoftbilgisistemleri-my.sharepoint.com/personal/aybuke_altuntas_ensight_com_tr/Documents/salesdata/"]}[Content],
				    ImportedCSV = Csv.Document(#"dim_date csv_https://mayasoftbilgisistemleri-my sharepoint com/personal/aybuke_altuntas_ensight_com_tr/Documents/salesdata/",[Delimiter=",", Columns=8, Encoding=1254, QuoteStyle=QuoteStyle.None]),
				    #"Tanıtılan Üst Bilgiler" = Table.PromoteHeaders(ImportedCSV, [PromoteAllScalars=true]),
				    #"Değiştirilen Tür" = Table.TransformColumnTypes(#"Tanıtılan Üst Bilgiler",{{"Date", type date}, {"Year", Int64.Type}, {"Quarter", Int64.Type}, {"Month", Int64.Type}, {"MonthName", type text}, {"Day", Int64.Type}, {"DayOfWeek", type text}, {"IsWeekend", type logical}})
				in
				    #"Değiştirilen Tür"

	annotation PBI_NavigationStepName = Gezinme

	annotation PBI_ResultType = Table

