table order_items
	lineageTag: 81bf3ee5-e94d-4e55-a4b1-d2b2b4d7e370

	column order_item_id
		dataType: int64
		formatString: 0
		lineageTag: dea0fffd-f38b-4aa3-9ab8-90412583e19d
		summarizeBy: sum
		sourceColumn: order_item_id

		annotation SummarizationSetBy = Automatic

	column order_id
		dataType: int64
		formatString: 0
		lineageTag: 8ec477ad-d378-4205-ac42-6696a5d3c9f1
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: int64
		formatString: 0
		lineageTag: 93a28dd4-4488-4391-8201-531d76bcf4c1
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: int64
		formatString: 0
		lineageTag: fa335b4a-303b-4207-a225-33ee23eb66ff
		summarizeBy: sum
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	column unit_price
		dataType: int64
		formatString: 0
		lineageTag: d79cfcf5-905b-4ae3-bab7-ea2f24b4d81a
		summarizeBy: sum
		sourceColumn: unit_price

		annotation SummarizationSetBy = Automatic

	column line_total
		dataType: int64
		formatString: 0
		lineageTag: 6b8347ea-02ad-4963-ac6c-fd66b8f6f96b
		summarizeBy: sum
		sourceColumn: line_total

		annotation SummarizationSetBy = Automatic

	partition order_items = m
		mode: import
		source =
				let
				    Kaynak = anasorgu,
				    #"order_items csv_https://mayasoftbilgisistemleri-my sharepoint com/personal/aybuke_altuntas_ensight_com_tr/Documents/salesdata/" = Kaynak{[Name="order_items.csv",#"Folder Path"="https://mayasoftbilgisistemleri-my.sharepoint.com/personal/aybuke_altuntas_ensight_com_tr/Documents/salesdata/"]}[Content],
				    ImportedCSV = Csv.Document(#"order_items csv_https://mayasoftbilgisistemleri-my sharepoint com/personal/aybuke_altuntas_ensight_com_tr/Documents/salesdata/",[Delimiter=",", Columns=6, Encoding=1254, QuoteStyle=QuoteStyle.None]),
				    #"Tanıtılan Üst Bilgiler" = Table.PromoteHeaders(ImportedCSV, [PromoteAllScalars=true]),
				    #"Değiştirilen Tür" = Table.TransformColumnTypes(#"Tanıtılan Üst Bilgiler",{{"order_item_id", Int64.Type}, {"order_id", Int64.Type}, {"product_id", Int64.Type}, {"quantity", Int64.Type}, {"unit_price", Int64.Type}, {"line_total", Int64.Type}})
				in
				    #"Değiştirilen Tür"

	annotation PBI_NavigationStepName = Gezinme

	annotation PBI_ResultType = Table

