table orders
	lineageTag: 5d78b53e-f837-4d78-a221-36853a942fd9

	column order_id
		dataType: int64
		formatString: 0
		lineageTag: fb5ef5cd-36c8-4523-8f34-2126122ba690
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: int64
		formatString: 0
		lineageTag: 17ebeefc-ec89-4de3-a948-bb5a1f2dc4fb
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column seller_id
		dataType: int64
		formatString: 0
		lineageTag: f3b59b2f-808a-4107-a852-98e2ec9ff69f
		summarizeBy: none
		sourceColumn: seller_id

		annotation SummarizationSetBy = Automatic

	column order_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: c2c5560e-1b9a-4f49-8b17-2d043d1f0c33
		summarizeBy: none
		sourceColumn: order_date

		variation Varyasyon
			isDefault
			relationship: 5022439c-b276-4a41-8512-5b159ebd0945
			defaultHierarchy: LocalDateTable_32051409-681a-40c5-a1b0-d5cf36216d60.'Tarih Hiyerarşisi'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column order_status
		dataType: string
		lineageTag: 53b1d67b-0eef-4da1-836d-86befd95d01e
		summarizeBy: none
		sourceColumn: order_status

		annotation SummarizationSetBy = Automatic

	column total_amount
		dataType: int64
		formatString: 0
		lineageTag: 1e0fdb79-8f86-4fdf-9ee9-39f3c5a2322e
		summarizeBy: sum
		sourceColumn: total_amount

		annotation SummarizationSetBy = Automatic

	partition orders = m
		mode: import
		source =
				let
				    Kaynak = anasorgu,
				    #"orders csv_https://mayasoftbilgisistemleri-my sharepoint com/personal/aybuke_altuntas_ensight_com_tr/Documents/salesdata/" = Kaynak{[Name="orders.csv",#"Folder Path"="https://mayasoftbilgisistemleri-my.sharepoint.com/personal/aybuke_altuntas_ensight_com_tr/Documents/salesdata/"]}[Content],
				    ImportedCSV = Csv.Document(#"orders csv_https://mayasoftbilgisistemleri-my sharepoint com/personal/aybuke_altuntas_ensight_com_tr/Documents/salesdata/",[Delimiter=",", Columns=6, Encoding=1254, QuoteStyle=QuoteStyle.None]),
				    #"Tanıtılan Üst Bilgiler" = Table.PromoteHeaders(ImportedCSV, [PromoteAllScalars=true]),
				    #"Değiştirilen Tür" = Table.TransformColumnTypes(#"Tanıtılan Üst Bilgiler",{{"order_id", Int64.Type}, {"customer_id", Int64.Type}, {"seller_id", Int64.Type}, {"order_date", type datetime}, {"order_status", type text}, {"total_amount", Int64.Type}}),
				    #"Değiştirilen Tür1" = Table.TransformColumnTypes(#"Değiştirilen Tür",{{"order_date", type date}})
				in
				    #"Değiştirilen Tür1"

	annotation PBI_NavigationStepName = Gezinme

	annotation PBI_ResultType = Table

