table payments
	lineageTag: 12e4a805-99b4-42d9-808d-c94881c1d81f

	column payment_id
		dataType: int64
		formatString: 0
		lineageTag: 16ec3d14-cb5c-4f33-82be-9af2d2cd9009
		summarizeBy: sum
		sourceColumn: payment_id

		annotation SummarizationSetBy = Automatic

	column order_id
		dataType: int64
		formatString: 0
		lineageTag: a4c31209-4d49-4a79-adbf-1912b7192665
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column payment_method
		dataType: string
		lineageTag: b24f228f-54c0-480e-9b0f-49c90855461a
		summarizeBy: none
		sourceColumn: payment_method

		annotation SummarizationSetBy = Automatic

	column payment_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 91fa997f-cf48-457c-acbe-193d39ee1967
		summarizeBy: none
		sourceColumn: payment_date

		variation Varyasyon
			isDefault
			relationship: 0505e098-4166-4326-923f-9fa7bdeea9ce
			defaultHierarchy: LocalDateTable_524ed732-6444-41ac-9cf1-25ecd4c985d6.'Tarih Hiyerarşisi'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column payment_status
		dataType: string
		lineageTag: 84f27e4d-b452-4678-aabb-c0888d556787
		summarizeBy: none
		sourceColumn: payment_status

		annotation SummarizationSetBy = Automatic

	column amount
		dataType: int64
		formatString: 0
		lineageTag: a8d833ca-27bb-4e7e-9a20-86554004f722
		summarizeBy: sum
		sourceColumn: amount

		annotation SummarizationSetBy = Automatic

	partition payments = m
		mode: import
		source =
				let
				    Kaynak = anasorgu,
				    #"payments csv_https://mayasoftbilgisistemleri-my sharepoint com/personal/aybuke_altuntas_ensight_com_tr/Documents/salesdata/" = Kaynak{[Name="payments.csv",#"Folder Path"="https://mayasoftbilgisistemleri-my.sharepoint.com/personal/aybuke_altuntas_ensight_com_tr/Documents/salesdata/"]}[Content],
				    ImportedCSV = Csv.Document(#"payments csv_https://mayasoftbilgisistemleri-my sharepoint com/personal/aybuke_altuntas_ensight_com_tr/Documents/salesdata/",[Delimiter=",", Columns=6, Encoding=1254, QuoteStyle=QuoteStyle.None]),
				    #"Tanıtılan Üst Bilgiler" = Table.PromoteHeaders(ImportedCSV, [PromoteAllScalars=true]),
				    #"Değiştirilen Tür" = Table.TransformColumnTypes(#"Tanıtılan Üst Bilgiler",{{"payment_id", Int64.Type}, {"order_id", Int64.Type}, {"payment_method", type text}, {"payment_date", type datetime}, {"payment_status", type text}, {"amount", Int64.Type}}),
				    #"Değiştirilen Tür1" = Table.TransformColumnTypes(#"Değiştirilen Tür",{{"payment_date", type date}})
				in
				    #"Değiştirilen Tür1"

	annotation PBI_NavigationStepName = Gezinme

	annotation PBI_ResultType = Table

