table products
	lineageTag: 62a023f7-ddd8-427b-8971-b234636b7f88

	column product_id
		dataType: int64
		formatString: 0
		lineageTag: f9019d7d-5c16-4da1-9317-870f935374f8
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column category_id
		dataType: int64
		formatString: 0
		lineageTag: a109530a-cdad-4e7f-a8fc-ad8ff11d38ca
		summarizeBy: none
		sourceColumn: category_id

		annotation SummarizationSetBy = Automatic

	column product_name
		dataType: string
		lineageTag: a80e044e-30b7-48c1-9339-adbca7b9bed5
		summarizeBy: none
		sourceColumn: product_name

		annotation SummarizationSetBy = Automatic

	column sku
		dataType: string
		lineageTag: d7b3dedc-0bea-4b97-b8fb-72af2389584e
		summarizeBy: none
		sourceColumn: sku

		annotation SummarizationSetBy = Automatic

	column unit_price
		dataType: int64
		formatString: 0
		lineageTag: 923bd40f-b713-4b47-b3f9-391a2fcf00e2
		summarizeBy: sum
		sourceColumn: unit_price

		annotation SummarizationSetBy = Automatic

	column stock_quantity
		dataType: int64
		formatString: 0
		lineageTag: c5b9e0b8-9780-4a26-a716-c8aa6b90ba54
		summarizeBy: sum
		sourceColumn: stock_quantity

		annotation SummarizationSetBy = Automatic

	column is_active
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 717fde18-5d96-4fd4-a63e-60255991c1a6
		summarizeBy: none
		sourceColumn: is_active

		annotation SummarizationSetBy = Automatic

	partition products = m
		mode: import
		source =
				let
				    Kaynak = anasorgu,
				    #"products csv_https://mayasoftbilgisistemleri-my sharepoint com/personal/aybuke_altuntas_ensight_com_tr/Documents/salesdata/" = Kaynak{[Name="products.csv",#"Folder Path"="https://mayasoftbilgisistemleri-my.sharepoint.com/personal/aybuke_altuntas_ensight_com_tr/Documents/salesdata/"]}[Content],
				    ImportedCSV = Csv.Document(#"products csv_https://mayasoftbilgisistemleri-my sharepoint com/personal/aybuke_altuntas_ensight_com_tr/Documents/salesdata/",[Delimiter=",", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Tanıtılan Üst Bilgiler" = Table.PromoteHeaders(ImportedCSV, [PromoteAllScalars=true]),
				    #"Değiştirilen Tür" = Table.TransformColumnTypes(#"Tanıtılan Üst Bilgiler",{{"product_id", Int64.Type}, {"category_id", Int64.Type}, {"product_name", type text}, {"sku", type text}, {"unit_price", Int64.Type}, {"stock_quantity", Int64.Type}, {"is_active", type logical}})
				in
				    #"Değiştirilen Tür"

	annotation PBI_NavigationStepName = Gezinme

	annotation PBI_ResultType = Table

