table sellers
	lineageTag: 66b77cbe-9453-4d50-9b12-80dfc835e19c

	column seller_id
		dataType: int64
		formatString: 0
		lineageTag: ccc5f8c2-5104-4669-8bd1-e7e86ac6e550
		summarizeBy: none
		sourceColumn: seller_id

		annotation SummarizationSetBy = Automatic

	column seller_name
		dataType: string
		lineageTag: 1dbde4fc-9813-44eb-8c2f-71b3eb768105
		summarizeBy: none
		sourceColumn: seller_name

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: 94a304e0-81f8-42ad-ad93-5fb022562c86
		summarizeBy: none
		sourceColumn: email

		annotation SummarizationSetBy = Automatic

	column phone
		dataType: int64
		formatString: 0
		lineageTag: c382593e-daab-4cf4-aecd-92807a2e64ae
		summarizeBy: none
		sourceColumn: phone

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: 30dce0c4-8e2c-42fb-b830-dc4a6a59b3b5
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column commission_rate
		dataType: int64
		formatString: 0
		lineageTag: dd3738bd-9d77-4043-ac86-4a9e5bfa5107
		summarizeBy: none
		sourceColumn: commission_rate

		annotation SummarizationSetBy = Automatic

	partition sellers = m
		mode: import
		source =
				let
				    Kaynak = anasorgu,
				    #"sellers csv_https://mayasoftbilgisistemleri-my sharepoint com/personal/aybuke_altuntas_ensight_com_tr/Documents/salesdata/" = Kaynak{[Name="sellers.csv",#"Folder Path"="https://mayasoftbilgisistemleri-my.sharepoint.com/personal/aybuke_altuntas_ensight_com_tr/Documents/salesdata/"]}[Content],
				    ImportedCSV = Csv.Document(#"sellers csv_https://mayasoftbilgisistemleri-my sharepoint com/personal/aybuke_altuntas_ensight_com_tr/Documents/salesdata/",[Delimiter=",", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Tanıtılan Üst Bilgiler" = Table.PromoteHeaders(ImportedCSV, [PromoteAllScalars=true]),
				    #"Değiştirilen Tür" = Table.TransformColumnTypes(#"Tanıtılan Üst Bilgiler",{{"seller_id", Int64.Type}, {"seller_name", type text}, {"email", type text}, {"phone", Int64.Type}, {"city", type text}, {"commission_rate", Int64.Type}})
				in
				    #"Değiştirilen Tür"

	annotation PBI_NavigationStepName = Gezinme

	annotation PBI_ResultType = Table

